### ISSUE TITLE
Go1.6 creates error with signal handlers

### ISSUE THREAD

**Issue by viblo** [rainycape/magick#37]
I get this error when I use this library together with a signal handler in go1.6 (go 1.5 is fine)

`signal 2 received but handler not on signal stack`
`fatal error: non-Go code set up signal handler without SA_ONSTACK flag`

My signal code looks like this

> c := make(chan os.Signal, 1)
> signal.Notify(c, syscall.SIGINT, syscall.SIGTERM)
> go func() {
> 	sig := <-c
> 	log.Printf("Received %+v", sig)
> }()

**Comment by rainycape** [comment]
@viblo I've checked both the IM and GM backends and I can't find any places in the C code that are setting up any signal handlers. magick tells IM and GM to not mess with signals and both seem to comply.

Just to make sure, I've also run the package tests with breakpoints set on any function that alter the signals and the tests finish without hitting any breakpoint.

What this means is that the bug is either in your code or in Go 1.6.

**Comment by viblo** [comment]
Here is a complete test program that crashes every time I ctrl-c or kill it in some other way: 
```
package main

import (
	"log"
	"os"
	"os/signal"
	"syscall"

	_ "github.com/rainycape/magick"
)

func main() {
	c := make(chan os.Signal, 1)
	signal.Notify(c, syscall.SIGINT, syscall.SIGTERM)

	sig := <-c
	log.Printf("Received %+v", sig)
}

```
The error comes from this https://golang.org/src/runtime/signal1_unix.go which was added in this commit: https://github.com/golang/go/commit/f7e51c132059a78953b768ca66e457b40985930e

If you are sure its not inside magick (i use the gm backend) then i guess I have to report it as a go 1.6 bug, because my code should be correct, right?

**Comment by rainycape** [comment]
@viblo Thanks for the complete program, it definitely makes testing things on my end easier.

I'm going to reopen this issue and investigate it further. I'll post an update later today.

**Comment by rainycape** [comment]
@viblo I've been able to reproduce the problem and I've also got a workaround working. I'll be pushing a fix in a few minutes.
